### ISSUE TITLE
Doesn't install correctly from pip

### ISSUE THREAD

**Issue by FoamyGuy** [adafruit/Adafruit_CircuitPython_RSA#26]
I think pip installations of this library do not work properly. 

In a test environment I installed with:
```
❯ pip install adafruit-circuitpython-rsa
Collecting adafruit-circuitpython-rsa
  Downloading adafruit-circuitpython-rsa-1.2.6.tar.gz (49 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 49.7/49.7 KB 7.0 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: Adafruit-Blinka in ./testing_venv/lib/python3.8/site-packages (from adafruit-circuitpython-rsa) (7.1.0)
Requirement already satisfied: Adafruit-PlatformDetect>=3.13.0 in ./testing_venv/lib/python3.8/site-packages (from Adafruit-Blinka->adafruit-circuitpython-rsa) (3.20.1)
Requirement already satisfied: Adafruit-PureIO>=1.1.7 in ./testing_venv/lib/python3.8/site-packages (from Adafruit-Blinka->adafruit-circuitpython-rsa) (1.1.9)
Requirement already satisfied: pyftdi>=0.40.0 in ./testing_venv/lib/python3.8/site-packages (from Adafruit-Blinka->adafruit-circuitpython-rsa) (0.53.3)
Requirement already satisfied: pyusb!=1.2.0,>=1.0.0 in ./testing_venv/lib/python3.8/site-packages (from pyftdi>=0.40.0->Adafruit-Blinka->adafruit-circuitpython-rsa) (1.2.1)
Requirement already satisfied: pyserial>=3.0 in ./testing_venv/lib/python3.8/site-packages (from pyftdi>=0.40.0->Adafruit-Blinka->adafruit-circuitpython-rsa) (3.5)
Using legacy 'setup.py install' for adafruit-circuitpython-rsa, since package 'wheel' is not installed.
Installing collected packages: adafruit-circuitpython-rsa
  Running setup.py install for adafruit-circuitpython-rsa ... done
Successfully installed adafruit-circuitpython-rsa-1.2.6
```

It completes successfully, but then if I try to use it:
```
>>> import adafruit_rsa
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'adafruit_rsa'
```

At least one problem leading to this is `py_modules` instead of `packages` here in the setup.py file: https://github.com/adafruit/Adafruit_CircuitPython_RSA/blob/56e5bad31e51ca93c631bdbf3ad567aaefbd91ea/setup.py#L54

**Comment by FoamyGuy** [comment]
Maybe we should opt for `setup.py.disabled` in this library. If the copy installed via pip hasn't been noticed until now it seems likely it's unused. 

Once you do get it installed the next hurdle is that it requires `adafruit_logging`
```
>>> import adafruit_rsa
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/timc/repos/circuitpython/Pip_Testing_Environment/testing_venv/lib/python3.8/site-packages/adafruit_rsa/__init__.py", line 16, in <module>
    from adafruit_rsa.key import newkeys, PrivateKey, PublicKey
  File "/home/timc/repos/circuitpython/Pip_Testing_Environment/testing_venv/lib/python3.8/site-packages/adafruit_rsa/key.py", line 25, in <module>
    import adafruit_logging as logging
ModuleNotFoundError: No module named 'adafruit_logging'
```
Which isn't currently deployed on pypi: https://github.com/adafruit/Adafruit_CircuitPython_Logging/blob/main/setup.py.disabled

If my understanding is correct anyone in an environment with access to pip would likely be using a CPython rsa implementation rather than this one. I believe this is meant largely for microcontrollers. In the event that someone does want to use it in CPython for testing or any other reason they could always git clone or copy/paste it as needed so it would still be possible to use the same way, just not deployed via pypi

**Comment by FoamyGuy** [comment]
This is resolved now. All libraries are deployed to pypi now so this does properly install including the logging dependency now.
