### ISSUE TITLE
rsa-512 private key exhausts stack

### ISSUE THREAD

**Issue by richardanaya** [adafruit/Adafruit_CircuitPython_RSA#31]
https://gist.github.com/richardanaya/3ab380003bb6544046039aa689906a81

```
code.py output:
Traceback (most recent call last):
  File "code.py", line 9, in <module>
  File "/lib/adafruit_jwt.py", line 101, in generate
RuntimeError: pystack exhausted
```

**Comment by richardanaya** [comment]
I used the wrong parameters
